### ISSUE TITLE
Library agnostic Json manipulation

### ISSUE THREAD

**Issue by mathieuancelin** [ReactiveCouchbase/reactivecouchbase-rs-core#10]
As discussed in #8 with @milenkovicm, with need to be able to use any Json lib we want

**Comment by milenkovicm** [comment]
I'm trying to familiarise with the library, please correct me if I'm wrong.
We could start with `N1qlQuery` (and other classes there), `params` should be `Any` under the hood Json library of choice should convert them to proper JSON type. 

Other thing to consider is to have `insert`, `get`, `upsert` which would use string as the type, to avoid stringify operation

**Comment by igorynia** [comment]
Marking data classes as `Any` is not the best idea. By using `Any` we limit the way how library determines concrete data types to reflection-only.

Currently, all the methods have implicit `Writes` or `Reads`, but they are from Play-Json. I think, what we should do, is to introduce our own Reads and Writes, and implement them for play-json ones. By doing that we won't break play-json support and would be able to give developers a way to implement their own Reads and Writes for their library of choice. What do you think?

**Comment by milenkovicm** [comment]
I'd say @mathieuancelin has implemented it like that already

**Comment by mathieuancelin** [comment]
@igorynia yes, it's already working this way. Play Json is optional and you can use any json lib you want.

https://github.com/ReactiveCouchbase/reactivecouchbase-rs-core#what-if-i-want-to-use-a-json-lib-other-than-play-json-
