### ISSUE TITLE
Feature Request - Publish binaries

### ISSUE THREAD

**Issue by etspaceman** [ReactiveCouchbase/reactivecouchbase-rs-core#12]
It would be great if we could publish the reactivecouchbase-rs-core library so that users did not have to clone / build / publish these locally.

**Comment by mathieuancelin** [comment]
It's already published

https://github.com/ReactiveCouchbase/reactivecouchbase-rs-core#if-you-want-to-try-it

just add 

```scala
resolvers += "reactivecouchbase-rs-snapshots" at "https://raw.github.com/ReactiveCouchbase/reactivecouchbase-rs-core/master/repository/snapshots"

libraryDependencies += "org.reactivecouchbase" %% "reactivecouchbase-rs-core" % "1.0.0-SNAPSHOT"
``` 

to your sbt build

**Comment by etspaceman** [comment]
Hey @mathieuancelin - Sorry for the late reply here. That makes sense. Can we start tagging versions of this library when new code is added? Its particularly hard to use the SNAPSHOT here because the code changes very often. It would be great to have minor version updates with our commits, e.g. 0.0.1, 0.0.2, etc.

**Comment by etspaceman** [comment]
Awesome. Thanks!!
