### ISSUE TITLE
Retry strategy 

### ISSUE THREAD

**Issue by HimanshuArora1234** [ReactiveCouchbase/reactivecouchbase-rs-core#14]
Hello, It's more an inquiry than an issue. How can we change the retry strategy (algo) in this lib ? Is there a RetryWhenFunction / RetryBuilder identical to java couchbase client ? If so, could you please let me know how it is done in reactive couchbase. Thanks a lot in advance. You people are doing a great job !!

**Comment by HimanshuArora1234** [comment]
Hello again,
Just like to add another quick question, could you be able to give me an idea when the version 1.0.0 or reactive couchbase be released ? Thanks again.

**Comment by mathieuancelin** [comment]
Hi @HimanshuArora1234 

can you give me an example of retry, or a link to, with the java client ?

**Comment by mathieuancelin** [comment]
about v 1.0.0, i'd love to finish the sub-document/data structures part of the API.

And maybe have to users to try it on actual project to have some feedback

**Comment by mathieuancelin** [comment]
I guess something like the following should work

```scala
object Retries {

  import scala.concurrent._
  import scala.concurrent.duration._
  import akka.pattern.after
  import akka.actor.Scheduler

  def retryOnError[T](retries: Int = 1, delay: FiniteDuration = 0.millis)(f: => Future[T])(implicit ec: ExecutionContext, s: Scheduler): Future[T] = {
    f recoverWith { case _ if retries > 0 => after(delay, s)(retryOnError(retries - 1, delay)(f)) }
  }
}

object TestRetries {

  import akka.actor.ActorSystem
  import scala.concurrent.duration._
  import scala.util._

  val actorSystem = ActorSystem()
  implicit val ec = actorSystem.dispatcher
  implicit val sched = actorSystem.scheduler

  def doSomethingWithCouchbase(): Future[String] = {
    println("good")
    Future.successful("SUCCESS")
  }

  def doSomethingWrongWithCouchbase(): Future[String] = {
    println("wrong")
    Future.successful("SUCCESS")
  }

  retryOnError(3, 2.millis) {
    doSomethingWithCouchbase()
  } andThen {
    case Success(msg) => println("successful")
    case Failure(e) => println("error :(")
  } // prints "good", then "successful"

  retryOnError(3, 2.millis) {
    doSomethingWrongWithCouchbase()
  } andThen {
    case Success(msg) => println("successful")
    case Failure(e) => println("error :(")
  } // prints "wrong", "wrong", "wrong", then "error :("
}
```

**Comment by HimanshuArora1234** [comment]
Hello Mathieu,

Thanks a lot for your quick reply. To answer your question about the RetryBuilder of java client, here goes the API link on that :

http://docs.couchbase.com/sdk-api/couchbase-java-client 2.2.7/com/couchbase/client/java/util/retry/RetryBuilder.html

Let me know if you need a concrete java example on that. 

Secondly Yeah I think the above snippet of code you added (_object Retries_) should do the trick :) Really appreciate this. 

I was curious about the 1.0.0 release because I really want to use this in a professional project for one of my clients. It's easy to convince them when it's a released version. So I guess this can actually be beneficial to you as well to get some feedback as you mentioned.

**Comment by HimanshuArora1234** [comment]
Hello again Mathieu,

I tried to use reactive couchbase in a Play project (using play 2.5). As soon as I added the sbt dependency for 1.0.0.0-snapshot, the project doesn't compile because of the following error 

`No Json serializer found for type org.joda.time.DateTime. Try to implement an implicit Writes or Format for this type.
`
Please note that this project compile and works fine without reactive couchbase dependency, no joda DataTime serialization/deser error whatsoever. I even tried to exclude the _play-josn_ transitive dependency coming with reactive couchbase to avoid any sort of conflict because of different versions of play but it did not fix the error. 

Do you have an idea what might be causing this error .. ? Thanks :)

**Comment by mathieuancelin** [comment]
I guess that's because `reactivecouchbase` uses play-json 2.6 that does not come with JodaTime reads/writes. 

You can try to exclude it from the `reactivecouchbase` dependencies in your `build.sbt` file and use your own `JsonReads` and `JsonWrite` (from `reactivecouchbase`) to transform your data the way you want

**Comment by HimanshuArora1234** [comment]
Hey Mathieu, Thanks a lot for taking time to reply. Appreciated !!
Yes it was my first reflex, I did exclude the play-json 2.6 coming with reactive couchbase but it did not help. Anyway as you said I implemented my own Reads/Writes for Joda DateTime to fix this problem. Thanks :)
