### ISSUE TITLE
Example with ViewQuery

### ISSUE THREAD

**Issue by joques** [ReactiveCouchbase/reactivecouchbase-rs-core#2]
Hi,
could you possibly add an example with ViewQuery? I am trying to implement one but don't know how to structure it. I am mostly lost regarding the result: QueryResult[ViewRow[T], NotUsed.
An example will certainly clarify things for me.
Thanks

**Comment by mathieuancelin** [comment]
Hi,

I guess you can do something like

```scala
val usersUnder43: Future[Seq[JsValue]] = bucket.searchView(
  ViewQuery("persons", "by_age", _.stale(Stale.FALSE).includeDocs(true).startKey(0).endKey(42)) ).flatMap(d => Source.fromFuture(d.doc)).asSeq
```

**Comment by mathieuancelin** [comment]
@joques does it work for you ?

**Comment by mathieuancelin** [comment]
@joques I'll close the issue for the moment but feel free to reopen it if you encounter issues
