### ISSUE TITLE
Error during the load the dependencies...

### ISSUE THREAD

**Issue by Yvvann** [ReactiveCouchbase/reactivecouchbase-rs-core#3]
Hi! excuse me, but I have an error during the load the dependencies:

libraryDependencies += "org.reactivecouchbase" % "reactivecouchbase-core" % "2.0.0-SNAPSHOT"

Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving io.apigee#rhino;1.7R5pre4 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving com.typesafe.play#build-link;2.5.4 ...
[info] Resolving com.typesafe#config;1.3.0 ...
[info] Resolving org.scala-sbt#logging;0.13.11 ...
[info] Resolving org.scala-sbt#tracking;0.13.11 ...
[info] Resolving javax.inject#javax.inject;1 ...
[info] Resolving com.typesafe.akka#akka-persistence-experimental_2.10;2.3.11 ...
[info] Resolving org.apache.maven#maven-core;3.2.2 ...
[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.3.3 ...
[info] Resolving org.scala-sbt#control;0.13.11 ...
[info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
[info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: download failed: org.reactivecouchbase#reactivecouchbase-core_2.11;2.0.0-SNAPSHOT!reactivecouchbase-core_2.11.jar
[error] (*:ssExtractDependencies) sbt.ResolveException: download failed: org.reactivecouchbase#reactivecouchbase-core_2.11;2.0.0-SNAPSHOT!reactivecouchbase-core_2.11.jar
[error] Total time: 7 s, completed May 4, 2017 9:18:19 PM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0</pre><br/>See complete log in <a href="C:\Users\Herson\.IdeaIC2016.2\system\log\sbt.last.log">C:\Users\Herson\.IdeaIC2016.2\system\log\sbt.last.log</a> 

>sbt publishing-local
[info] Packaging C:\WorkSpace\workplay\couchdemo\reactivecouchbase-rs-core\target\scala-2.11\reactivecouchbase-core_2.11-2.0.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info]  published reactivecouchbase-core_2.11 to C:\Users\Herson\.ivy2\local\org.reactivecouchbase\reactivecouchbase-core_2.11\2.0.0-SNAPSHOT\poms\reactivecouchbase-core_2.11.pom
[info]  published reactivecouchbase-core_2.11 to C:\Users\Herson\.ivy2\local\org.reactivecouchbase\reactivecouchbase-core_2.11\2.0.0-SNAPSHOT\jars\reactivecouchbase-core_2.11.jar
[info]  published reactivecouchbase-core_2.11 to C:\Users\Herson\.ivy2\local\org.reactivecouchbase\reactivecouchbase-core_2.11\2.0.0-SNAPSHOT\srcs\reactivecouchbase-core_2.11-sources.jar
[info]  published reactivecouchbase-core_2.11 to C:\Users\Herson\.ivy2\local\org.reactivecouchbase\reactivecouchbase-core_2.11\2.0.0-SNAPSHOT\docs\reactivecouchbase-core_2.11-javadoc.jar
[info]  published ivy to C:\Users\Herson\.ivy2\local\org.reactivecouchbase\reactivecouchbase-core_2.11\2.0.0-SNAPSHOT\ivys\ivy.xml
[success] Total time: 7 s, completed May 4, 2017 9:10:07 PM

Thanks in advance!!

**Comment by mathieuancelin** [comment]
Hi, 

that's because reactivecouchbase 2.0.0 is not published anywhere, you have to publish it on your local repo.

```
sbt ';clean;compile;publish-local'
```
