### ISSUE TITLE
Rename package name

### ISSUE THREAD

**Issue by igorynia** [ReactiveCouchbase/reactivecouchbase-rs-core#6]
In one of my projects I am thinking to start an update process, moving some functionality from the old library to the new one. And I think it would be better to live some time with these two libraries. But it's impossible to have two libraries simultaneously, due to the same package names.
I would propose to change the package name to different one, what do you think?

**Comment by mathieuancelin** [comment]
Done.

package is now `reactivecouchbase-rs-core` and java packages are now `org.reactivecouchbase.rs`
